### ISSUE TITLE
Unresolved Externals when installing on windows

### ISSUE THREAD

**Issue by WhoWouldaThunk** [kovidgoyal/html5-parser#2]
I followed the instructions at https://html5-parser.readthedocs.io/en/latest/#windows
to build for windows. And this is what I get when I run 

python.exe win-ci.py install_deps

from a vs command prompt.

lxml.etree.obj : error LNK2001: unresolved external symbol xmlMemDisplayLast
build\lib.win-amd64-3.5\lxml\etree.cp35-win_amd64.pyd : fatal error LNK1120: 230 unresolved externals

[buildFail.txt](https://github.com/kovidgoyal/html5-parser/files/1086872/buildFail.txt)

**Comment by WhoWouldaThunk** [comment]
Was just reading through the txt and I notice this on line 627/8

ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
** make sure the development packages of libxml2 and libxslt are installed **

Not sure if that helps or not.

**Comment by kovidgoyal** [comment]
Sigh, windows is such a pain :)

That error does not matter because the include and library directory paths are specified directly by the build script. Look At the last command in the log, it includes

/LIBPATH:D:/Downloads/html5-parser-master/sw/lib

That directory will contain libxml2.lib which has those symbol definitions. Why the linker is not picking them up, I dont know. All I can tell you is that it works on CI server. See https://github.com/kovidgoyal/html5-parser/blob/master/.appveyor.yml

which does basically three steps:

1) Setup the visual studio command propmy environment
2) Run the win-ci.py install_deps
3) Run win-ci.py test
